name: Code Scan

on:
  workflow_dispatch:
    
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

   #   - name: Secret Scan with Gitleaks
   #     uses: gitleaks/gitleaks-action@v2
   #     env:
   #       GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}

      - name: Secret Scan with TruffleHog
        uses: trufflesecurity/trufflehog@main
        with:
          path: .
          output: trufflehog-results.json
