name: Code Scan

on:
  workflow_dispatch:
    
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install TruffleHog
        run: pip install trufflehog

      - name: Run TruffleHog and Save Output
        run: trufflehog filesystem --json . > trufflehog-results.json

      - name: Upload TruffleHog Results
        uses: actions/upload-artifact@v4
        with:
          name: trufflehog-report
          path: trufflehog-results.json



